services:
    eliza:
        command: ["pnpm", "start", "--character=./characters/angel0x.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        env_file:
            - .env
        environment:
            - SERVER_PORT=3000
        ports:
            - "3000:3000"
        restart: always
